openapi: 3.0.0
info:
  title: eCommerce-tshirtStore
  description: Tshirts Store API
  version: 1.0.0
  contact:
    email: beesettim27@gmail.com
    url: "https://Manu.in"

# servers:
#   - url : "https://localhost:4000/api/v1"
#     description: For local host - secure
#   - url : "http://localhost:4000/api/v1"
#     description: For local host - regular

servers:
  # - url: "{protocol}://api-doc.up.railway.app/api/{version}"
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host, version
    variables:
      version:
        default: v1
        enum:
          - v1
          - v2
      protocol:
        default: http
        enum:
          - https
          - http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in : cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - JSON
      summary: returns a whelcome msg in JSON
      responses:
        200:
          desciption: success
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message : Hello From dummy page
        400:
          description: Bad request
        500:
          description: Internal Error
